version: '3.8'
services: 
  api:
    container_name: Server_container
    restart: always
    build: ./node_serv
    ports: 
      - "8081:8081"
    depends_on: 
      - mongo
  client:
    container_name: client-container
    restart: always
    build: ./hw
    ports: 
      - "8080:8080"
    depends_on: 
      - api
  mongo:
    container_name: mongo-backend
    image: mongo
    expose: 
      - "27017"
    ports: 
      - "27017:27017"
    volumes: 
      - apiDB:/data/db

volumes: 
  apiDB:
